version: '3'
services:
  fpnode:
    container_name: fpnode
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 2200:2200
    volumes:
      - ./app/:/var/www/html:rw
  # nginx:
  #   #container_name: reverse
  #   image: nginx
  #   #hostname: reverse
  #   ports:
  #     - 80:80
  #     - 443:443
  #   environment:
  #     - NGINX_HOST=presidenten.miguelbilliet.be
  #     - NGINX_PORT=80
  #   volumes:
  #     - ./data/nginx/:/etc/nginx/conf.d/:rw
  #     - ./data/certbot/conf:/etc/letsencrypt
  #     - ./data/certbot/www:/var/www/certbot
  #   command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  # certbot:
  #   container_name: certbot
  #   image: certbot/certbot
  #   volumes:
  #     - ./data/certbot/conf:/etc/letsencrypt
  #     - ./data/certbot/www:/var/www/certbot
  #   entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"